// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SurviveOnSotka.Db;

namespace SurviveOnSotka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descriptrion");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<Guid?>("ParentCategoryId");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.CheapPlace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<Guid>("CityId");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("CheapPlaces");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.FileModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Path")
                        .IsRequired();

                    b.Property<Guid?>("RecipeId");

                    b.Property<Guid?>("ReviewIdRecipe");

                    b.Property<Guid?>("ReviewIdUserWhoGiveReview");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("ReviewIdRecipe", "ReviewIdUserWhoGiveReview");

                    b.ToTable("FileModels");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Ingredient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IconId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<Guid?>("TypeFoodId");

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.HasIndex("TypeFoodId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.IngredientToRecipe", b =>
                {
                    b.Property<Guid>("IdRecipe");

                    b.Property<Guid>("IdIngredient");

                    b.Property<int>("Amount");

                    b.Property<Guid>("IngredientId");

                    b.Property<int>("Price");

                    b.Property<Guid>("RecipeId");

                    b.Property<int>("Weight");

                    b.HasKey("IdRecipe", "IdIngredient");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientToRecipe");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Level", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("LastLevelId");

                    b.Property<int>("MaxScore");

                    b.Property<int>("MinScore");

                    b.HasKey("Id");

                    b.HasIndex("LastLevelId")
                        .IsUnique()
                        .HasFilter("[LastLevelId] IS NOT NULL");

                    b.ToTable("Levels");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.RateReview", b =>
                {
                    b.Property<Guid>("IdReview");

                    b.Property<Guid>("IdUserWhoGiveMark");

                    b.Property<bool>("IsCool");

                    b.Property<Guid?>("ReviewIdRecipe");

                    b.Property<Guid?>("ReviewIdUserWhoGiveReview");

                    b.Property<string>("UserWhoGiveMarkId");

                    b.HasKey("IdReview", "IdUserWhoGiveMark");

                    b.HasIndex("UserWhoGiveMarkId");

                    b.HasIndex("ReviewIdRecipe", "ReviewIdUserWhoGiveReview");

                    b.ToTable("RateReviews");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AuthorId")
                        .IsRequired();

                    b.Property<Guid>("CategoryId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<string>("Description");

                    b.Property<Guid?>("FirstStepId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime>("TimeForCooking");

                    b.Property<DateTime>("TimeForPreparetion");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FirstStepId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Review", b =>
                {
                    b.Property<Guid>("IdRecipe");

                    b.Property<Guid>("IdUserWhoGiveReview");

                    b.Property<string>("AuthorId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<int>("Rate")
                        .HasMaxLength(5);

                    b.Property<Guid?>("RecipeId");

                    b.Property<string>("Text");

                    b.HasKey("IdRecipe", "IdUserWhoGiveReview");

                    b.HasIndex("AuthorId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<Guid?>("NextStepId");

                    b.Property<Guid?>("PhotoId");

                    b.HasKey("Id");

                    b.HasIndex("NextStepId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Steps");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.Property<Guid?>("RecipeId");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.TypeFood", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IconId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12);

                    b.HasKey("Id");

                    b.HasIndex("IconId");

                    b.ToTable("TypeFoods");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AboutYourself");

                    b.Property<int>("AccessFailedCount");

                    b.Property<Guid?>("AvatarId");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<int>("CurrentScore");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<bool>("Gender");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<Guid>("LevelId");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("LevelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Category", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.CheapPlace", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.FileModel", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.Recipe")
                        .WithMany("Photos")
                        .HasForeignKey("RecipeId");

                    b.HasOne("SurviveOnSotka.Model.Entities.Review")
                        .WithMany("Photos")
                        .HasForeignKey("ReviewIdRecipe", "ReviewIdUserWhoGiveReview");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Ingredient", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.FileModel", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId");

                    b.HasOne("SurviveOnSotka.Model.Entities.TypeFood", "TypeFood")
                        .WithMany()
                        .HasForeignKey("TypeFoodId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.IngredientToRecipe", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SurviveOnSotka.Model.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Level", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.Level", "LastLevel")
                        .WithOne("NextLevel")
                        .HasForeignKey("SurviveOnSotka.Model.Entities.Level", "LastLevelId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.RateReview", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.User", "UserWhoGiveMark")
                        .WithMany()
                        .HasForeignKey("UserWhoGiveMarkId");

                    b.HasOne("SurviveOnSotka.Model.Entities.Review", "Review")
                        .WithMany()
                        .HasForeignKey("ReviewIdRecipe", "ReviewIdUserWhoGiveReview");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Recipe", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SurviveOnSotka.Model.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SurviveOnSotka.Model.Entities.Step", "FirstStep")
                        .WithMany()
                        .HasForeignKey("FirstStepId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Review", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("SurviveOnSotka.Model.Entities.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Step", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.Step", "NextStep")
                        .WithMany()
                        .HasForeignKey("NextStepId");

                    b.HasOne("SurviveOnSotka.Model.Entities.FileModel", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.Tag", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.Recipe")
                        .WithMany("Tags")
                        .HasForeignKey("RecipeId");
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.TypeFood", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.FileModel", "Icon")
                        .WithMany()
                        .HasForeignKey("IconId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SurviveOnSotka.Model.Entities.User", b =>
                {
                    b.HasOne("SurviveOnSotka.Model.Entities.FileModel", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId");

                    b.HasOne("SurviveOnSotka.Model.Entities.Level", "Level")
                        .WithMany()
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
